### ISSUE TITLE
Docker building

### ISSUE THREAD

**Issue by frodrigo** [kartotherian/kartotherian#116]
I'm lost trying to build the docker.
I finally figure the Dockefile was generated.
The committed Dokerfile is useful or not? Can be removed?

**Comment by thesocialdev** [comment]
@frodrigo take a look at https://github.com/thesocialdev/kartodock

**Comment by frodrigo** [comment]
Thank. But I removed kartotherian from my project last week. Replaced by by a modified tileserver-gl.
