### ISSUE TITLE
Dynamic style and "island map" support

### ISSUE THREAD

**Issue by benstadin** [kartotherian/kartotherian#17]
I would like to implement dynamically updateable style and island map support. The use-case I'm thinking of is like this:
- Given some external tool, a user can extract part of a map. This part will be copied into an own database for isolated editing and viewing.
- Given another external style editing tool, a user makes changes to an existing style - or creates a new named style. 
- The map can then be viewed via http://mymap/?source=default/?s=osm

How can I change the config loading and related modules so that I could then for example use a simple scheme to store source and style configs in a directors structure like:
configs/sourceName/styles/styleName

Example content:
configs/default/source.yaml
configs/default/styles/osm <-- osm-bright-style copy
configs/myMapOfNY/source.yaml
configs/myMapOfNY/styles/myNYStyle/ <-- editable copy of osm-bright-style

Is it possible?

~Ben

**Comment by nyurik** [comment]
The sources system could be fairly easily changed on-the-fly - you simply give it a new configuration. Actually this is exactly what happens in tilerator - in the admin tool the new sources are set via a web form.  The dir structure is really up to you - any path would work.
