### ISSUE TITLE
JSON specs

### ISSUE THREAD

**Issue by hyperknot** [kartotherian/kartotherian#19]
What is the format of the served JSON files? 

The wiki page says: 

> you can also use "json" to see the GeoJSON data

but it is clearly not GeoJSON, but some custom JSON data. Is it documented somewhere?

**Comment by MaxSem** [comment]
It's just PBFs https://github.com/mapbox/vector-tile-spec but serialized to JSON. This format is not intended for anything but debugging.

**Comment by nyurik** [comment]
@hyperknot , thanks for the comment, fixed it on the wiki page

**Comment by hyperknot** [comment]
Thanks for the clarification. BTW, is there a gitter room or email group where people can ask questions like this?

**Comment by nyurik** [comment]
hmm... http://gis.stackexchange.com/ ?

**Comment by hyperknot** [comment]
But I mean, specific to this project. Stackexchange really doesn't like discussions, but if you prefer I can ask future questions there.

**Comment by nyurik** [comment]
Well, there is a maps mailing list - https://lists.wikimedia.org/mailman/listinfo/maps-l
where we could have some discussions that relate to wikipedia's maps project.  There is bug/task tracker  phabricator with maps tag - https://phabricator.wikimedia.org/tag/maps/ 
and there is these issues here and stackexchange.  On top of it, people have been discussing various issues on the talk page - https://www.mediawiki.org/wiki/Talk:Maps

**Comment by hyperknot** [comment]
Thanks a lot, subscribed.
