### ISSUE TITLE
wikidata entry does not satisfy notability requirements

### ISSUE THREAD

**Issue by ghost** [kartotherian/kartotherian#24]
Hi,
Unless I'm mistaken, the https://www.wikidata.org/wiki/Q25975588 entry for kartotherian that was added today does not meet the [notability requirements](https://www.wikidata.org/wiki/Wikidata:Notability).
Did I miss something ?
Cheers

**Comment by MaxSem** [comment]
- Issues with Wikidata pages should go to Wikidata.
- Wikidata's inclusion policy is quite different from Wikipedia's one.

**Comment by ghost** [comment]
@MaxSem would you like to be informed of how kartotherian is referenced in wikidata / wikipedia ?
