### ISSUE TITLE
Duplicated tiles

### ISSUE THREAD

**Issue by Rudloff** [kartotherian/kartotherian#26]
Hello,

At higher zoom levels, the wrong tiles are displayed:
![capture d ecran 2016-10-28 a 11 46 53](https://cloud.githubusercontent.com/assets/840125/19802503/516703c4-9d04-11e6-876b-f748c832542c.png)
(https://maps.wikimedia.org/#17/48.58548/7.75050)

**Comment by nyurik** [comment]
I think this was fixed a while ago. Please reopen if you still see it.
