### ISSUE TITLE
No longer necessary installation steps

### ISSUE THREAD

**Issue by marcosox** [kartotherian/kartotherian#39]
Hi, I am following the readme to install kartotherian, but I found some minor issues in the installation steps:

- no need to add dependencies since they seem to be already included in package.json
- no need to add `"@kartotherian/tilelive-http",` to the `registerSourceLibs` section (already there)
- System dependencies are not installed automatically.
  I figured out I needed to install on my debian 9 x64:
    - pkg-config
    - libcairo2-dev
    - libjpeg-dev
    - libgif-dev
    - libmapnik-dev
(only after installing I found the actual dependencies in the package.json file)

**Comment by Phyks** [comment]
@mdholloway This issue could probably be closed as it is likely to be solved after #78.
