### ISSUE TITLE
Gl view

### ISSUE THREAD

**Issue by frodrigo** [kartotherian/kartotherian#8]
Please, can you explicite how to use the gl vector view in the readme ? It's working by default ?
(I successfully setup a running kartotherian with png tiles)

**Comment by Ecologeek** [comment]
go to the static/mapbox-gl-js folder
run 'npm install'

in your browser go to the url /static/gl/ and it should work

I never made it to work on my laptop (gentoo) due to an error with node-gyp, but it should be working on ubuntu/debian

**Comment by frodrigo** [comment]
Ok, it's working

**Comment by frodrigo** [comment]
PL in Readme done.
