### ISSUE TITLE
invalid city-name, i dont get it..

### ISSUE THREAD

**Issue by ka7** [kartotherian/kartotherian#84]
hi,
( this is most-likely not a bug, but a head-scratching case. i don't get it...)
( also, this points to the "production" version maps.wikimedia.org -- as used in wikidata.org ..  )

working on 
https://www.wikidata.org/wiki/Q183104
the geo shows this map
https://maps.wikimedia.org/img/osm-intl,13,47.238055555556,9.5983333333334,310x180.png?lang=en

The name of the city shows "**Sogn Pieder**", but should be "**Feldkirch**"

this seems to be the "räteromanisch" ( = a language) name of the city. ( https://de.wikipedia.org/wiki/Feldkirch )
This makes no sense. Räterromanisch is a small, valid language in Switzerland (nearby), but no official one in Austria.

For me this looks like: at as some-point-in-time this was as-is in the data.
With "current" i cant re-create this behavior. ( i can also switch the "?lang=en" to "de", "fr".. nothing changes )

Maybe some "very stable" server side caching issue ?

.ka7

**Comment by MaxSem** [comment]
For the reference, this is https://maps.wikimedia.org/?uselang=en#13/47.2381/9.5982 and specifically this tile: https://maps.wikimedia.org/osm-intl/13/4314/2873@1.3x.png?lang=en (JSON: https://maps.wikimedia.org/osm-intl/13/4314/2873@1.3x.json?lang=en ). Looks like the language picking algorithm prefers choosing *any* definite language to default label.

**Comment by mooeypoo** [comment]
@mdholloway Head's up -- got a patch up in Babel. I am having trouble locally testing this (I don't have the entire stack running locally anymore), but I added a test for the specific edge case (with a comment to explain) so it should work well. If you still have the system set up for testing locally, please test, merge if good, and deploy; might need to update the npm package for babel + extension.json in kartotherian.

**Comment by Pikse** [comment]
This latinization part of language picker seems to be bugous in its other aspects too, or at least it doesn't do quite what the description says. It seems to pick language with Latn suffix where name key with different name variant already is in Latin script ([T195318](https://phabricator.wikimedia.org/T195318)) and it picks Latin-script name for language that isn't in Latin script ([T208927](https://phabricator.wikimedia.org/T208927)), while it doesn't pick up name with pinyin suffix for Latin-script language (like [Sanming](https://www.openstreetmap.org/node/244081697) name for Finnish [here](https://maps.wikimedia.org/osm-intl/8/211/108.png?lang=fi)). @mooeypoo, can you take a look?

**Comment by ka7** [comment]
btw: this fix is meanwhile reflected also now in maps.wikimedia.org. it shows the correct therm "Feldkirch"
thanks.
