### ISSUE TITLE
Restructuring code to monorepo

### ISSUE THREAD

**Issue by nyurik** [kartotherian/kartotherian#87]
It has been fairly difficult to manage tens of separate repos that contain small semi-related packages, especially when migrating one package required updates to another one.  It seems a good solution to this is a common practice of combining code into a `mono-repo`.  All code is placed inside a single repository as separate "package" sub-directories, but each package is maintained and published separately. Also, there are tools that help with managing it, e.g. [Lerna](https://github.com/lerna/lerna#readme), which handles NPM linking, common versioning, etc.

# Plan
* Rename `kartotherian/master` branch to `kartotherian/legacy`
* Using `git merge`, combine all repositories into a single repository `kartotherian` with the following structure:
  * `/README.md`
  * `/lerna.json`
  * `/packages/kartotherian`
  * `/packages/tilerator`
  * `/packages/babel`
  * Root dir will contain scripts, build tools, styles, docs, and anything else related to the system as a whole rather than an individual package.
* Archive other repos once everything works, redirecting them to the corresponding package

CC: @mateusbs17 @MaxSem @mdholloway

**Comment by mdholloway** [comment]
I have a demo of this up on GitHub at https://github.com/mdholloway/kartotherian-lerna.  If that looks about as expected, I'll open up a PR.

**Comment by mdholloway** [comment]
It does indeed make dependency management much easier!

**Comment by mdholloway** [comment]
@mateusbs17

**Comment by nyurik** [comment]
@mdholloway this is awesome!!! Thanks for tackling this.  I have been observing a very similar effort by https://github.com/vega/vega -- they recently did the same migration (I initially suggested it to them, but did not actually participate in the migration itself), and they ended up using `workspace` feature as being much easier to handle than the hackish Lerna-own dependency hoisting, and instead relies on yarn's native support for workspaces.  I think it would make sense for us to follow the same model and use their experience with this.

**Comment by nyurik** [comment]
@mdholloway I have re-done the merge in order to keep the original structure, and migrated to yarn. `yarn` supports workspaces, thus linking is done on the level of the package manager, not lerna (thus it is far more reliable). Also, I kept the `tilelive-vector` because it has been significantly altered in order to support language param passing. I'm not sure if WMF is using it, but I think we should keep it in the monorepo.  https://github.com/kartotherian/kartotherian/pull/89

**Comment by mdholloway** [comment]
Hey @nyurik, sorry but I've been head-down recently trying to get a new MW extension shipped for the Android team.  The yarn/workspaces approach sounds interesting and I hope to have a look soon.  In the meantime I'll close this PR, since it appears to be obsolete.
