### ISSUE TITLE
Store rendered png's

### ISSUE THREAD

**Issue by spalger** [kartotherian/kartotherian#94]
I was thinking about storing the rendered PNG's in cassandra, but it seems that this [is hard coded to store PBF's](https://github.com/kartotherian/kartotherian-cassandra/blob/master/CassandraStore.js#L35-L38). Is that the only way you would recommend doing it?

**Comment by nyurik** [comment]
I will close this as there is a workaround, plus there is no nearterm plan to support PNGs as "first class" object type.
