### ISSUE TITLE
sort hangs if sortFiles gets an empty list

### ISSUE THREAD

**Issue by saper** [kartotherian/kartotherian#98]
https://github.com/kartotherian/tilerator-jobprocessor/blob/master/lib/fileParser.js#L116 will hang on stdin if the list if empty.

Related-To: https://phabricator.wikimedia.org/T145534#2987786

**Comment by nyurik** [comment]
I am guessing that this issue has been resolved with the above patches from @MaxSem. Please advise if this isn't so.
